<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>8-1-5</title>
</head>
<body>
</body>
<script>
  /* finally 구문 사용 하지 않은 코드 */

  /* 
  throw문은 사용자 정의 예외를 발생(throw)할 수 있습니다. 
  예외가 발생하면 현재 함수의 실행이 중지되고 (throw 이후의 명령문은 실행되지 않습니다.), 제어 흐름은 콜스택의 첫 번째 catch 블록으로 전달됩니다. 호출자 함수 사이에 catch 블록이 없으면 프로그램이 종료됩니다. 
  */
  function test() {
    try{
      alert('A 위치입니다.')
      throw "예외 강제 발생"
    }catch(exception){
      alert('B 위치입니다')
      return
    }
    //finally 구문 없이
    alert('C 위치입니다.') // 실행하지 않음
  }

  // 함수 호출
  test()

</script>
</html>